version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: taski_db
      POSTGRES_USER: taski_user
      POSTGRES_PASSWORD: taski_password

  backend:
    build:
      context: ./backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://taski_user:taski_password@db:5432/taski_db
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/static

volumes:
  postgres_data:
  static_volume:
